services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-docker-app:latest
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    external: true
    name: ${MY_NETWORK:-deployagent_default}